name: healthy_purr_mobile_app
description: Mobile application for the Healthy Purr project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.2
  async: ^2.8.1
  bordered_text: ^2.0.0
  camera: ^0.9.4+18
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  flutter_native_image: ^0.0.6+1
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  grouped_buttons_ns: ^1.0.0
  google_ml_kit: ^0.7.3
  http: ^0.13.4
  image: ^3.1.1
  image_picker: ^0.8.4+4
  jumping_dot: ^0.0.4
  page_transition: ^2.0.4
  provider: ^6.0.1
  progress_indicators: ^1.0.0
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  simple_animations: ^4.0.1
  string_validator: ^0.3.0
  string_similarity: ^2.0.0
  top_snackbar_flutter: ^1.0.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
